export type AgreementTemplateType = "CONFIDENTIALITY" | "NON_COMPETE";

const company = "Trung Tâm Phẫu Thuật Tạo Hình Thẩm Mỹ — Bệnh Viện Đa Khoa Hồng Phúc";
const address = "Số 5 Hồ Xuân Hương, Hồng Bàng, Hải Phòng";

export function agreementTitle(type: AgreementTemplateType): string {
  return type === "CONFIDENTIALITY"
    ? "THỎA THUẬN BẢO MẬT THÔNG TIN VÀ BẢO VỆ BÍ MẬT KINH DOANH"
    : "THỎA THUẬN KHÔNG CẠNH TRANH VÀ KHÔNG LÔI KÉO KHÁCH HÀNG, NHÂN SỰ";
}

export function buildAgreementTemplate(type: AgreementTemplateType, staff: { fullName: string; nationalId: string | null; position: string | null }): string {
  const person = staff.fullName || "…………………………………………";
  const id = staff.nationalId || "……………………";
  const position = staff.position || "……………………";
  if (type === "CONFIDENTIALITY") {
    return `CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM\nĐộc lập – Tự do – Hạnh phúc\n\n${agreementTitle(type)}\n\nBÊN A — BÊN SỬ DỤNG LAO ĐỘNG\nTên đơn vị: ${company}\nĐịa chỉ: ${address}\nNgười đại diện: Ông Lê Đình Lam — Giám đốc điều hành\n\nBÊN B — NGƯỜI LAO ĐỘNG\nHọ và tên: ${person}\nSố CCCD: ${id}\nChức danh/Vị trí: ${position}\n\nĐIỀU 1. THÔNG TIN BẢO MẬT\nThông tin bảo mật bao gồm danh sách khách hàng và khách hàng tiềm năng; họ tên, số điện thoại, địa chỉ, email, mạng xã hội; hồ sơ tư vấn, lịch sử dịch vụ, hình ảnh trước/sau và thông tin sức khỏe; bảng giá, chiết khấu, khuyến mãi, hoa hồng, định mức; nguồn khách, marketing, kịch bản tư vấn, quy trình bán hàng; bí mật kinh doanh, công nghệ, nhà cung cấp, đối tác; thông tin nhân sự, tài chính và mọi tài liệu nội bộ của Bên A. Thông tin bảo mật không phụ thuộc hình thức lưu trữ và thuộc quyền quản lý của Bên A.\n\nĐIỀU 2. NGHĨA VỤ CỦA BÊN B\nBên B giữ bí mật, chỉ sử dụng dữ liệu cho công việc được giao, không sao chép/chụp màn hình/chuyển ra thiết bị cá nhân, không lưu số khách vào tài khoản cá nhân, sử dụng tài khoản chính thức đúng quy định và báo ngay khi phát hiện rò rỉ.\n\nĐIỀU 3. QUYỀN SỞ HỮU DỮ LIỆU\nKhách hàng do Bên B tiếp nhận, tư vấn hoặc phục vụ trong thời gian làm việc là khách hàng của Bên A. Dữ liệu phải được cập nhật đầy đủ vào hệ thống, không được giữ riêng.\n\nĐIỀU 4. THỜI HẠN\nNghĩa vụ có hiệu lực từ ngày ký trong thời gian làm việc và tiếp tục 72 tháng sau khi chấm dứt quan hệ lao động.\n\nĐIỀU 5. BÀN GIAO\nKhi chấm dứt công việc hoặc khi Bên A yêu cầu, Bên B phải bàn giao và xóa dữ liệu, tài liệu, tài khoản do Bên A cấp, đồng thời ký xác nhận không còn lưu giữ thông tin bảo mật.\n\nĐIỀU 6. VI PHẠM\nViệc xử lý kỷ luật, bồi thường và khoản phạt (nếu có) phải được rà soát, điều chỉnh để phù hợp pháp luật và nội quy lao động hiện hành trước khi ký chính thức.\n\nĐIỀU 7. ĐIỀU KHOẢN CHUNG\nMọi sửa đổi phải lập thành văn bản. Thỏa thuận lập thành hai bản, mỗi bên giữ một bản và có hiệu lực từ ngày ký.\n\nĐẠI DIỆN BÊN A                              BÊN B\n(Ký, ghi rõ họ tên, đóng dấu)                (Ký, ghi rõ họ tên)\n`;
  }
  return `CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM\nĐộc lập – Tự do – Hạnh phúc\n\n${agreementTitle(type)}\n\nBÊN A — BÊN SỬ DỤNG LAO ĐỘNG\nTên đơn vị: ${company}\nĐịa chỉ: ${address}\nNgười đại diện: Ông Lê Đình Lam — Giám đốc điều hành\n\nBÊN B — NGƯỜI LAO ĐỘNG\nHọ và tên: ${person}\nSố CCCD: ${id}\nChức danh/Vị trí: ${position}\n\nĐIỀU 1. GIẢI THÍCH\nĐối thủ cạnh tranh là cá nhân/tổ chức kinh doanh dịch vụ thẩm mỹ, làm đẹp, phẫu thuật thẩm mỹ, spa hoặc dịch vụ tương tự. Khách hàng là khách hàng/khách hàng tiềm năng Bên B đã tiếp xúc, tư vấn hoặc biết thông tin khi làm việc. Lôi kéo là hành vi trực tiếp hoặc gián tiếp mời gọi khách hàng hoặc nhân sự của Bên A chuyển sang Bên B hoặc bên thứ ba.\n\nĐIỀU 2. KHÔNG LÔI KÉO KHÁCH HÀNG\nTrong thời gian làm việc và thời hạn sau khi chấm dứt được hai bên xác nhận, Bên B không lôi kéo, lấy đi, sử dụng dữ liệu hoặc cung cấp dịch vụ ngoài phạm vi công việc cho khách hàng của Bên A.\n\nĐIỀU 3. KHÔNG LÔI KÉO NHÂN SỰ\nBên B không trực tiếp hoặc gián tiếp rủ rê người lao động của Bên A nghỉ việc hoặc chuyển sang làm việc cho Bên B/bên thứ ba trong thời hạn đã thỏa thuận.\n\nĐIỀU 4. KHÔNG CẠNH TRANH\nPhạm vi, thời hạn và địa bàn hạn chế cạnh tranh phải được hai bên xác nhận là hợp lý, cần thiết và được rà soát pháp lý trước khi ký. Mẫu nội bộ đang tham chiếu bán kính 15 km và thời hạn 24 tháng, nhưng không tự động coi đây là điều khoản hợp lệ nếu chưa được chuyên gia rà soát.\n\nĐIỀU 5. VI PHẠM VÀ BỒI THƯỜNG\nMức bồi thường, phạt và giới hạn trách nhiệm phải được rà soát theo pháp luật và quan hệ lao động cụ thể trước khi ký chính thức.\n\nĐIỀU 6. HIỆU LỰC SAU CHẤM DỨT\nCác nghĩa vụ đã ký tiếp tục theo phạm vi, thời hạn và điều kiện được ghi trong bản chính thức.\n\nĐIỀU 7. ĐIỀU KHOẢN CHUNG\nMọi sửa đổi phải lập thành văn bản. Thỏa thuận lập thành hai bản, mỗi bên giữ một bản và có hiệu lực từ ngày ký.\n\nĐẠI DIỆN BÊN A                              BÊN B\n(Ký, ghi rõ họ tên)                         (Ký, ghi rõ họ tên)\n`;
}
