import Link from "next/link";
import { FolderKanban, ShieldCheck } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { V2DemoSeedButton } from "@/components/v2-demo-seed-button";

export const dynamic = "force-dynamic";

export default async function ProjectsPage() {
  await requireUser(["ADMIN", "MANAGER"]);
  if (process.env.ENABLE_ZENITH_V2 !== "true") return <div className="space-y-4"><header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-sm font-medium text-brand-600">Nền tảng vận hành</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Dự án</h1><p className="mt-2 text-sm leading-6 text-slate-500">Lớp đa Dự án đang khóa để bảo toàn hệ thống clinic hiện tại. Bật `ENABLE_ZENITH_V2=true` trong môi trường test để mở.</p></header><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-800">Chưa truy vấn bảng V2 khi feature flag tắt. Điều này giúp migration chưa chạy không làm gián đoạn ứng dụng cũ.</div></div>;
  const projects = await prisma.zProject.findMany({ orderBy: { updatedAt: "desc" }, include: { _count: { select: { members: true, units: true, mechanisms: true } } } });
  return <div className="space-y-6"><header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><FolderKanban className="h-5 w-5" /></span><div><p className="text-sm font-medium text-brand-600">Nền tảng vận hành</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Dự án</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Mỗi Dự án có tổ chức, cơ chế, quyền và dữ liệu riêng. Bản nháp phải mô phỏng và duyệt trước khi áp dụng.</p></div></div><V2DemoSeedButton /></div></header><div className="grid gap-4">{projects.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center text-sm text-slate-500">Chưa có Dự án. Hãy tạo dữ liệu demo để bắt đầu kiểm thử.</div> : projects.map((project) => <article key={project.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><div className="flex items-center gap-2"><h2 className="font-semibold text-slate-900">{project.name}</h2><span className="rounded-full bg-emerald-50 px-2 py-0.5 text-xs font-medium text-emerald-700">{project.status}</span></div><p className="mt-1 text-sm text-slate-500">{project.code} · {project.description ?? "Chưa có mô tả"}</p><p className="mt-2 text-xs text-slate-400">{project._count.units} bộ phận · {project._count.mechanisms} cơ chế · {project._count.members} thành viên</p></div><div className="flex flex-wrap gap-2"><Link href={`/du-an/${project.id}/to-chuc`} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Tổ chức</Link><Link href={`/du-an/${project.id}/co-che`} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Cơ chế</Link></div></div></article>)}</div><div className="flex items-start gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-800"><ShieldCheck className="mt-0.5 h-5 w-5" /><p>V2 demo chỉ dùng dữ liệu giả. Cơ chế đang ở DRAFT; chưa tính vào lương, đơn hàng hay settlement thật.</p></div></div>;
}
