import Link from "next/link";
import { ArrowLeft, CalendarDays, ShieldCheck } from "lucide-react";
import { V2WorkspaceAppointmentForm, V2WorkspaceAppointmentStatusForm } from "@/components/v2-workspace-appointment-form";
import { prisma } from "@/lib/db";
import { requireProjectModule } from "@/lib/v2-access";
import { normalizedModuleKeys } from "@/lib/v2-modules";

export const dynamic = "force-dynamic";

const statusLabel: Record<string, string> = { BOOKED: "Đã đặt", CONFIRMED: "Đã xác nhận", ARRIVED: "Đã đến", IN_CONSULT: "Đang tư vấn", IN_SERVICE: "Đang làm", DONE: "Hoàn thành", CANCELLED: "Đã hủy", NO_SHOW: "Không đến" };
const statusTone: Record<string, string> = { BOOKED: "bg-blue-50 text-blue-700", CONFIRMED: "bg-indigo-50 text-indigo-700", ARRIVED: "bg-cyan-50 text-cyan-700", IN_CONSULT: "bg-amber-50 text-amber-700", IN_SERVICE: "bg-orange-50 text-orange-700", DONE: "bg-emerald-50 text-emerald-700", CANCELLED: "bg-slate-100 text-slate-500", NO_SHOW: "bg-rose-50 text-rose-700" };

export default async function ProjectAppointmentsPage({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params;
  const { project } = await requireProjectModule(projectId, "appointments", { activeOnly: true });
  const enabled = new Set(normalizedModuleKeys(project.enabledFeatures));
  const moduleEnabled = enabled.has("appointments");
  const appointments = moduleEnabled ? await prisma.zWorkspaceAppointment.findMany({ where: { projectId: project.id }, orderBy: { scheduledAt: "asc" }, include: { customer: { select: { code: true, fullName: true } }, assignedTo: { select: { fullName: true, username: true } } } }) : [];
  const customers = moduleEnabled ? await prisma.zWorkspaceCustomer.findMany({ where: { projectId: project.id, active: true }, select: { id: true, code: true, fullName: true }, orderBy: { fullName: "asc" } }) : [];
  const memberIds = moduleEnabled ? (await prisma.zProjectMember.findMany({ where: { projectId: project.id, active: true }, select: { userId: true } })).map((member) => member.userId) : [];
  const members = memberIds.length ? await prisma.user.findMany({ where: { id: { in: memberIds }, active: true }, select: { id: true, fullName: true, username: true }, orderBy: { fullName: "asc" } }) : [];

  return <div className="space-y-6">
    <Link href={`/du-an/${project.id}`} className="inline-flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-slate-900"><ArrowLeft className="h-4 w-4" />Về workspace {project.name}</Link>
    <header className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><p className="text-sm font-medium text-brand-600">{project.code} · Module workspace</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Lịch hẹn</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Lịch hẹn của <strong>{project.name}</strong>, chỉ liên kết Customer local và thành viên active của Dự án.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-700"><ShieldCheck className="h-3.5 w-3.5" />Scope: {project.code}</span></div></header>
    {!moduleEnabled && <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-900">Module Lịch hẹn đang tắt trong workspace này. Admin có thể bật module tại <Link href={`/du-an/${project.id}`} className="font-semibold underline">trang workspace</Link>; thao tác bật/tắt không xóa dữ liệu.</section>}
    {moduleEnabled && <>
      <section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Tổng lịch</p><p className="mt-2 text-2xl font-bold text-slate-900">{appointments.length}</p><p className="mt-1 text-sm text-slate-500">Chỉ thuộc Dự án này</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Đã hoàn thành</p><p className="mt-2 text-2xl font-bold text-slate-900">{appointments.filter((appointment) => appointment.status === "DONE").length}</p><p className="mt-1 text-sm text-slate-500">Theo trạng thái local</p></div><div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Khách có thể chọn</p><p className="mt-2 text-2xl font-bold text-slate-900">{customers.length}</p><p className="mt-1 text-sm text-slate-500">Customer active cùng project</p></div></section>
      <V2WorkspaceAppointmentForm projectId={project.id} customers={customers} members={members} />
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-brand-600" /><h2 className="font-semibold text-slate-900">Lịch trong workspace</h2><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-semibold text-slate-600">{appointments.length}</span></div>{appointments.length === 0 ? <div className="mt-5 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center text-sm text-slate-500">Chưa có lịch hẹn. Tạo lịch đầu tiên để kiểm tra liên kết Customer và assignee cùng project.</div> : <div className="mt-4 space-y-3">{appointments.map((appointment) => <article key={appointment.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-slate-800">{new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short" }).format(appointment.scheduledAt)}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-semibold ${statusTone[appointment.status] ?? "bg-slate-100 text-slate-600"}`}>{statusLabel[appointment.status] ?? appointment.status}</span></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-2 text-xs text-slate-500"><span>Khách: {appointment.customer ? `${appointment.customer.code} · ${appointment.customer.fullName}` : "Chưa liên kết"}</span><span>Phụ trách: {appointment.assignedTo ? `${appointment.assignedTo.fullName} · @${appointment.assignedTo.username}` : "Chưa phân công"}</span></div>{appointment.serviceInterest && <p className="mt-2 text-sm text-slate-600">Dịch vụ: {appointment.serviceInterest}</p>}{appointment.note && <p className="mt-1 text-sm text-slate-500">{appointment.note}</p>}</div><V2WorkspaceAppointmentStatusForm projectId={project.id} appointmentId={appointment.id} status={appointment.status} /></div></article>)}</div>}</section>
    </>}
  </div>;
}
