"use client";

import { useEffect } from "react";
import { Archive, Check, Loader2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useFormAction } from "@/lib/use-form-action";
import { archiveWorkspaceCustomerAction, recordWorkspaceCustomerConsentAction, updateWorkspaceCustomerAction } from "@/lib/v2-customer-actions";

export function V2WorkspaceCustomerDetailForms({ projectId, customer }: { projectId: string; customer: { id: string; code: string; fullName: string; phoneLast4: string | null; source: string | null; note: string | null; consentStatus: string | null } }) {
  const router = useRouter();
  const [editState, editAction, editPending] = useFormAction(updateWorkspaceCustomerAction, () => router.refresh());
  const [consentState, consentAction, consentPending] = useFormAction(recordWorkspaceCustomerConsentAction, () => router.refresh());
  const [archiveState, archiveAction, archivePending] = useFormAction(archiveWorkspaceCustomerAction, () => router.refresh());
  useEffect(() => { if (editState.ok || consentState.ok || archiveState.ok) router.refresh(); }, [archiveState.ok, consentState.ok, editState.ok, router]);
  return <div className="space-y-4">
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Chỉnh sửa hồ sơ project-local</h2><form action={editAction} className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="customerId" value={customer.id} /><label className="text-sm text-slate-700">Mã khách<input required name="code" defaultValue={customer.code} className="mt-1 min-h-10 w-full rounded-lg border border-slate-200 px-3" /></label><label className="text-sm text-slate-700">Họ tên<input required name="fullName" defaultValue={customer.fullName} className="mt-1 min-h-10 w-full rounded-lg border border-slate-200 px-3" /></label><label className="text-sm text-slate-700">4 số cuối điện thoại<input name="phoneLast4" defaultValue={customer.phoneLast4 ?? ""} maxLength={4} className="mt-1 min-h-10 w-full rounded-lg border border-slate-200 px-3" /></label><label className="text-sm text-slate-700">Nguồn<input name="source" defaultValue={customer.source ?? ""} className="mt-1 min-h-10 w-full rounded-lg border border-slate-200 px-3" /></label><label className="text-sm text-slate-700 md:col-span-2">Ghi chú<textarea name="note" defaultValue={customer.note ?? ""} className="mt-1 min-h-24 w-full rounded-lg border border-slate-200 px-3 py-2" /></label><div className="md:col-span-2"><button disabled={editPending} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-slate-900 px-4 text-sm font-semibold text-white disabled:opacity-50">{editPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />} Lưu thay đổi</button></div></form>{editState.message && <p role="status" className="mt-3 text-sm text-emerald-700">{editState.message}</p>}{editState.error && <p role="alert" className="mt-3 text-sm text-rose-700">{editState.error}</p>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-900">Consent project-local</h2><form action={consentAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="customerId" value={customer.id} /><label className="text-sm text-slate-700">Trạng thái<select name="consentStatus" defaultValue={customer.consentStatus ?? "PENDING"} className="mt-1 min-h-10 rounded-lg border border-slate-200 px-3"><option value="PENDING">PENDING</option><option value="GRANTED">GRANTED</option><option value="REFUSED">REFUSED</option></select></label><label className="min-w-64 flex-1 text-sm text-slate-700">Ghi chú<textarea name="consentNote" className="mt-1 min-h-10 w-full rounded-lg border border-slate-200 px-3 py-2" /></label><button disabled={consentPending} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white disabled:opacity-50">{consentPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />} Ghi consent</button></form>{consentState.message && <p role="status" className="mt-3 text-sm text-emerald-700">{consentState.message}</p>}{consentState.error && <p role="alert" className="mt-3 text-sm text-rose-700">{consentState.error}</p>}</section>
    <section className="rounded-2xl border border-rose-200 bg-rose-50 p-5"><h2 className="font-semibold text-rose-900">Tạm dừng hồ sơ</h2><p className="mt-1 text-sm text-rose-800">Không xóa dữ liệu. Hồ sơ chuyển inactive, giữ lịch sử và có audit.</p><form action={archiveAction} className="mt-3 flex items-end gap-3"><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="customerId" value={customer.id} /><label className="text-sm text-rose-900">Nhập ARCHIVE<input required name="confirmation" placeholder="ARCHIVE" className="mt-1 min-h-10 rounded-lg border border-rose-200 bg-white px-3 uppercase" /></label><button disabled={archivePending} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-rose-700 px-4 text-sm font-semibold text-white disabled:opacity-50">{archivePending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Archive className="h-4 w-4" />} Tạm dừng</button></form>{archiveState.message && <p role="status" className="mt-3 text-sm text-emerald-700">{archiveState.message}</p>}{archiveState.error && <p role="alert" className="mt-3 text-sm text-rose-700">{archiveState.error}</p>}</section>
  </div>;
}
